"use server";

import { auth } from "@/auth/auth";
import { db } from ".";
import { cuisineTable, recipeTable } from "./schemas/recipe-schema";
import { getUniqueRecipeSlug } from "@/utils/helpers";

export async function seed() {
  const { user } = await auth.api.createUser({
    body: {
      email: "chetkara@gmail.com",
      name: "Julian",
      data: {
        username: "barrelrolla",
        displayUsername: "Barrelrolla",
        emailVerified: true,
        image:
          "https://res.cloudinary.com/dkvc3cs7o/image/upload/c_auto,g_auto,h_400,w_400/v1785421900/cook-it/user-avatars/barrelrolla.webp",
      },
      password: "Pass123$",
      role: "admin",
    },
  });
  console.log("added user", user.name);

  const cuisines = await db
    .insert(cuisineTable)
    .values([
      { name: "Albanian" },
      { name: "Austrian" },
      { name: "Belgian" },
      { name: "British" },
      { name: "Bulgarian" },
      { name: "Croatian" },
      { name: "Czech" },
      { name: "Danish" },
      { name: "Dutch" },
      { name: "Finnish" },
      { name: "French" },
      { name: "German" },
      { name: "Greek" },
      { name: "Hungarian" },
      { name: "Irish" },
      { name: "Italian" },
      { name: "Norwegian" },
      { name: "Polish" },
      { name: "Portuguese" },
      { name: "Romanian" },
      { name: "Serbian" },
      { name: "Spanish" },
      { name: "Swedish" },
      { name: "Swiss" },
      { name: "Ukrainian" },
      { name: "Egyptian" },
      { name: "Israeli" },
      { name: "Lebanese" },
      { name: "Moroccan" },
      { name: "Palestinian" },
      { name: "Persian" },
      { name: "Syrian" },
      { name: "Turkish" },
      { name: "Indian" },
      { name: "Pakistani" },
      { name: "Bangladeshi" },
      { name: "Sri Lankan" },
      { name: "Nepalese" },
      { name: "Chinese" },
      { name: "Japanese" },
      { name: "Korean" },
      { name: "Mongolian" },
      { name: "Filipino" },
      { name: "Indonesian" },
      { name: "Malaysian" },
      { name: "Singaporean" },
      { name: "Thai" },
      { name: "Vietnamese" },
      { name: "American" },
      { name: "Canadian" },
      { name: "Caribbean" },
      { name: "Cuban" },
      { name: "Mexican" },
      { name: "Peruvian" },
      { name: "Ethiopian" },
      { name: "South African" },
      { name: "Nigerian" },
      { name: "Tunisian" },
    ])
    .returning();

  console.log("added cuisinges");

  await db.insert(recipeTable).values({
    slug: getUniqueRecipeSlug("Creamy Mushroom Pasta"),
    title: "Creamy Mushroom Pasta",
    authorId: user.id,
    imageUrl:
      "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/creamy-mushroom-pasta_wgnb3j.png",
    category: "dinner",
    cuisineId: cuisines[15].id,
    description:
      "A rich and comforting pasta dish made with golden mushrooms, garlic, Parmesan, and a silky cream sauce. Ready in under 30 minutes, making it perfect for a cozy weeknight dinner.",
    prepTime: 10,
    cookTime: 20,
    difficulty: "easy",
    instructions: [
      "Bring a large pot of salted water to a boil. Cook the pasta according to the package instructions until al dente, then reserve about 1/2 cup of pasta water before draining.",
      "While the pasta cooks, clean the mushrooms and slice them evenly. Mince the garlic and grate the Parmesan.",
      "Heat olive oil in a large skillet over medium-high heat. Add the mushrooms and cook for 5-7 minutes until golden brown and most of their moisture has evaporated.",
      "Reduce the heat to medium and add the butter and minced garlic. Cook for about 30 seconds, until the garlic becomes fragrant.",
      "Pour in the heavy cream and bring it to a gentle simmer. Stir in the Parmesan and cook for 2-3 minutes until the sauce thickens.",
      "Add the drained pasta to the skillet and toss until evenly coated. Add a splash of reserved pasta water if the sauce is too thick.",
      "Season with salt and freshly ground black pepper. Serve immediately with additional Parmesan and fresh parsley.",
    ],
    ingredients: [
      "300 g pasta",
      "250 g cremini mushrooms",
      "3 cloves garlic",
      "2 tbsp olive oil",
      "1 tbsp butter",
      "200 ml heavy cream",
      "60 g Parmesan cheese",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
      "2 tbsp fresh parsley",
    ],
    servings: 4,
    diet: [],
  });

  await db.insert(recipeTable).values({
    slug: getUniqueRecipeSlug("Rainbow Buddha Bowl"),
    title: "Rainbow Buddha Bowl",
    authorId: user.id,
    imageUrl:
      "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
    category: "lunch",
    cuisineId: cuisines[47].id,
    description:
      "A colorful and satisfying grain bowl packed with roasted chickpeas, fresh vegetables, avocado, and a creamy tahini dressing.",
    prepTime: 15,
    cookTime: 25,
    difficulty: "easy",
    instructions: [
      "Preheat the oven to 200°C. Drain and rinse the chickpeas, then pat them dry with a clean kitchen towel.",
      "Toss the chickpeas with olive oil, paprika, cumin, salt, and pepper. Spread them on a baking sheet and roast for 20-25 minutes until golden and crispy.",
      "Cook the rice according to the package instructions. Once cooked, fluff with a fork and set aside.",
      "Prepare the vegetables while the rice and chickpeas cook. Slice the avocado, halve the cherry tomatoes, grate the carrot, and thinly slice the cucumber.",
      "Make the dressing by whisking together tahini, lemon juice, olive oil, garlic, and enough water to reach a smooth pouring consistency.",
      "Divide the rice between serving bowls. Arrange the roasted chickpeas and vegetables over the rice.",
      "Drizzle with tahini dressing and finish with fresh parsley and sesame seeds.",
    ],
    ingredients: [
      "200 g cooked rice",
      "1 can (400 g) chickpeas",
      "1 carrot",
      "1/2 cucumber",
      "150 g cherry tomatoes",
      "1 avocado",
      "2 tbsp olive oil",
      "1/2 tsp paprika",
      "1/2 tsp ground cumin",
      "1 tbsp sesame seeds",
      "2 tbsp fresh parsley",
      "2 tbsp tahini",
      "1 tbsp lemon juice",
      "1 small garlic clove",
      "Salt to taste",
      "Black pepper to taste",
    ],
    servings: 2,
    diet: ["vegan", "vegetarian"],
  });

  await db.insert(recipeTable).values({
    slug: getUniqueRecipeSlug("Honey Garlic Salmon"),
    title: "Honey Garlic Salmon",
    authorId: user.id,
    imageUrl:
      "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/honey-garlic-salmon_zfya0i.png",
    category: "dinner",
    cuisineId: cuisines[39].id,
    description:
      "Tender salmon fillets glazed with a sweet and savory honey garlic sauce. A quick dinner with crisp edges, a caramelized glaze, and plenty of flavor.",
    prepTime: 10,
    cookTime: 15,
    difficulty: "medium",
    instructions: [
      "Pat the salmon fillets dry with paper towels and season both sides lightly with salt and black pepper.",
      "In a small bowl, whisk together honey, soy sauce, minced garlic, lemon juice, and smoked paprika.",
      "Heat the olive oil in a large skillet over medium-high heat. Place the salmon skin-side up and cook for 3-4 minutes until golden brown.",
      "Carefully flip the salmon and cook for another 2 minutes.",
      "Pour the honey garlic sauce into the skillet. Reduce the heat to medium and spoon the sauce over the salmon as it simmers.",
      "Cook for another 4-6 minutes, occasionally basting the salmon, until it is cooked through and the glaze has thickened.",
      "Remove from the heat and garnish with sliced spring onion and sesame seeds. Serve immediately with rice or roasted vegetables.",
    ],
    ingredients: [
      "2 salmon fillets",
      "2 tbsp honey",
      "2 tbsp soy sauce",
      "3 cloves garlic",
      "1 tbsp lemon juice",
      "1/2 tsp smoked paprika",
      "1 tbsp olive oil",
      "1 spring onion",
      "1 tsp sesame seeds",
      "Salt to taste",
      "Black pepper to taste",
    ],
    servings: 2,
  });

  await db.insert(recipeTable).values({
    slug: getUniqueRecipeSlug("Chocolate Lava Cake"),
    title: "Chocolate Lava Cake",
    authorId: user.id,
    imageUrl:
      "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/chocolate-lava-cake_fqr7zl.png",
    category: "dessert",
    cuisineId: cuisines[10].id,
    description:
      "Individual chocolate cakes with a soft, molten center. These decadent desserts are surprisingly simple to prepare and are best served warm with vanilla ice cream.",
    prepTime: 20,
    cookTime: 12,
    difficulty: "hard",
    instructions: [
      "Preheat the oven to 200°C. Butter four small ramekins and dust the insides lightly with cocoa powder.",
      "Melt the dark chocolate and butter together in a heatproof bowl over a pan of gently simmering water. Stir until completely smooth, then remove from the heat.",
      "In a separate bowl, whisk the eggs, egg yolks, and sugar for 2-3 minutes until pale and slightly thickened.",
      "Slowly whisk the melted chocolate mixture into the egg mixture until smooth.",
      "Sift in the flour and salt. Fold gently until just combined, taking care not to overmix.",
      "Divide the batter evenly between the prepared ramekins and place them on a baking sheet.",
      "Bake for 10-12 minutes. The edges should be set while the centers remain slightly soft and jiggly.",
      "Let the cakes rest for 1 minute, then carefully invert each ramekin onto a serving plate.",
      "Serve immediately with vanilla ice cream, fresh berries, or a dusting of powdered sugar.",
    ],
    ingredients: [
      "120 g dark chocolate",
      "100 g butter",
      "2 large eggs",
      "2 egg yolks",
      "50 g granulated sugar",
      "40 g all-purpose flour",
      "1/4 tsp salt",
      "1 tsp cocoa powder",
      "Vanilla ice cream for serving",
      "Fresh berries for serving",
    ],
    servings: 4,
  });
  await db.insert(recipeTable).values([
    {
      slug: getUniqueRecipeSlug("Garlic Butter Chicken"),
      title: "Garlic Butter Chicken",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/creamy-mushroom-pasta_wgnb3j.png",
      category: "dinner",
      cuisineId: cuisines[1].id,
      description: "Juicy chicken cooked in a rich garlic butter sauce.",
      prepTime: 10,
      cookTime: 20,
      difficulty: "easy",
      instructions: [
        "Cook the chicken in garlic butter until golden and cooked through.",
      ],
      ingredients: ["2 chicken breasts"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Creamy Garlic Rice"),
      title: "Creamy Garlic Rice",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "side",
      cuisineId: cuisines[5].id,
      description:
        "Creamy rice with plenty of garlic and a comforting texture.",
      prepTime: 5,
      cookTime: 20,
      difficulty: "easy",
      instructions: ["Simmer the rice with garlic and cream until tender."],
      ingredients: ["200 g rice"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Honey Glazed Chicken"),
      title: "Honey Glazed Chicken",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/honey-garlic-salmon_zfya0i.png",
      category: "dinner",
      cuisineId: cuisines[7].id,
      description: "Tender chicken coated in a sweet and sticky honey glaze.",
      prepTime: 10,
      cookTime: 20,
      difficulty: "medium",
      instructions: [
        "Pan-fry the chicken and coat it with honey until caramelized.",
      ],
      ingredients: ["2 chicken thighs"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Vanilla Chocolate Cake"),
      title: "Vanilla Chocolate Cake",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/chocolate-lava-cake_fqr7zl.png",
      category: "dessert",
      cuisineId: cuisines[10].id,
      description: "A simple chocolate cake with a delicate vanilla flavor.",
      prepTime: 15,
      cookTime: 30,
      difficulty: "easy",
      instructions: [
        "Bake the chocolate batter until a toothpick comes out clean.",
      ],
      ingredients: ["150 g dark chocolate"],
      servings: 6,
    },
    {
      slug: getUniqueRecipeSlug("Crispy Chicken Bowl"),
      title: "Crispy Chicken Bowl",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "lunch",
      cuisineId: cuisines[33].id,
      description: "A colorful bowl topped with crispy golden chicken.",
      prepTime: 10,
      cookTime: 20,
      difficulty: "medium",
      instructions: ["Arrange crispy chicken over cooked rice and vegetables."],
      ingredients: ["150 g chicken"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Lemon Garlic Pasta"),
      title: "Lemon Garlic Pasta",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/creamy-mushroom-pasta_wgnb3j.png",
      category: "dinner",
      cuisineId: cuisines[15].id,
      description: "Bright and simple pasta tossed with lemon and garlic.",
      prepTime: 5,
      cookTime: 15,
      difficulty: "easy",
      instructions: ["Toss cooked pasta with lemon juice and sautéed garlic."],
      ingredients: ["250 g spaghetti"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Spicy Honey Salmon"),
      title: "Spicy Honey Salmon",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/honey-garlic-salmon_zfya0i.png",
      category: "dinner",
      cuisineId: cuisines[37].id,
      description: "Salmon glazed with honey and a touch of chili.",
      prepTime: 5,
      cookTime: 15,
      difficulty: "easy",
      instructions: ["Brush the salmon with honey and chili before roasting."],
      ingredients: ["2 salmon fillets"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Mini Chocolate Cakes"),
      title: "Mini Chocolate Cakes",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/chocolate-lava-cake_fqr7zl.png",
      category: "dessert",
      cuisineId: cuisines[12].id,
      description: "Small individual chocolate cakes perfect for dessert.",
      prepTime: 10,
      cookTime: 15,
      difficulty: "medium",
      instructions: [
        "Bake the individual cakes until the centers are just set.",
      ],
      ingredients: ["100 g chocolate"],
      servings: 4,
    },
    {
      slug: getUniqueRecipeSlug("Roasted Veggie Bowl"),
      title: "Roasted Veggie Bowl",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "lunch",
      cuisineId: cuisines[12].id,
      description: "Roasted vegetables served over a bed of fluffy grains.",
      prepTime: 10,
      cookTime: 25,
      difficulty: "easy",
      instructions: ["Roast the vegetables until browned and serve over rice."],
      ingredients: ["1 zucchini"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Butter Chicken"),
      title: "Butter Chicken",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/creamy-mushroom-pasta_wgnb3j.png",
      category: "dinner",
      cuisineId: cuisines[34].id,
      description: "Tender chicken simmered in a creamy spiced tomato sauce.",
      prepTime: 15,
      cookTime: 30,
      difficulty: "medium",
      instructions: ["Simmer cooked chicken in a creamy tomato sauce."],
      ingredients: ["300 g chicken"],
      servings: 4,
    },
    {
      slug: getUniqueRecipeSlug("Crispy Potato Bites"),
      title: "Crispy Potato Bites",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "snack",
      cuisineId: cuisines[3].id,
      description: "Golden bite-sized potatoes with crisp edges.",
      prepTime: 10,
      cookTime: 25,
      difficulty: "easy",
      instructions: ["Roast the potatoes until crisp and golden."],
      ingredients: ["400 g potatoes"],
      servings: 3,
    },
    {
      slug: getUniqueRecipeSlug("Garlic Butter Shrimp"),
      title: "Garlic Butter Shrimp",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/honey-garlic-salmon_zfya0i.png",
      category: "dinner",
      cuisineId: cuisines[20].id,
      description: "Juicy shrimp quickly cooked in fragrant garlic butter.",
      prepTime: 5,
      cookTime: 10,
      difficulty: "easy",
      instructions: [
        "Sauté the shrimp in garlic butter until pink and tender.",
      ],
      ingredients: ["300 g shrimp"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Dark Chocolate Tart"),
      title: "Dark Chocolate Tart",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/chocolate-lava-cake_fqr7zl.png",
      category: "dessert",
      cuisineId: cuisines[10].id,
      description:
        "A rich chocolate tart with a smooth dark chocolate filling.",
      prepTime: 20,
      cookTime: 30,
      difficulty: "hard",
      instructions: [
        "Bake the tart shell and fill it with melted dark chocolate.",
      ],
      ingredients: ["200 g dark chocolate"],
      servings: 6,
    },
    {
      slug: getUniqueRecipeSlug("Fresh Garden Bowl"),
      title: "Fresh Garden Bowl",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "salad",
      cuisineId: cuisines[12].id,
      description: "A fresh bowl packed with colorful vegetables.",
      prepTime: 10,
      cookTime: 0,
      difficulty: "easy",
      instructions: ["Combine the vegetables in a bowl and serve fresh."],
      ingredients: ["1 cucumber"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Creamy Tomato Pasta"),
      title: "Creamy Tomato Pasta",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/creamy-mushroom-pasta_wgnb3j.png",
      category: "dinner",
      cuisineId: cuisines[15].id,
      description: "Pasta coated in a creamy tomato sauce.",
      prepTime: 5,
      cookTime: 20,
      difficulty: "easy",
      instructions: ["Stir cooked pasta into the creamy tomato sauce."],
      ingredients: ["250 g pasta"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Sweet Chili Salmon"),
      title: "Sweet Chili Salmon",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/honey-garlic-salmon_zfya0i.png",
      category: "dinner",
      cuisineId: cuisines[37].id,
      description: "Salmon glazed with a sweet and mildly spicy sauce.",
      prepTime: 5,
      cookTime: 15,
      difficulty: "medium",
      instructions: ["Brush the salmon with sweet chili sauce and bake."],
      ingredients: ["2 salmon fillets"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Chocolate Brownie Bites"),
      title: "Chocolate Brownie Bites",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/chocolate-lava-cake_fqr7zl.png",
      category: "snack",
      cuisineId: cuisines[47].id,
      description: "Small fudgy chocolate brownies perfect for sharing.",
      prepTime: 10,
      cookTime: 18,
      difficulty: "easy",
      instructions: ["Bake the brownie mixture until fudgy in the center."],
      ingredients: ["100 g chocolate"],
      servings: 6,
    },
    {
      slug: getUniqueRecipeSlug("Mediterranean Grain Bowl"),
      title: "Mediterranean Grain Bowl",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "lunch",
      cuisineId: cuisines[12].id,
      description: "A wholesome grain bowl with fresh Mediterranean flavors.",
      prepTime: 10,
      cookTime: 15,
      difficulty: "easy",
      instructions: ["Combine cooked grains with vegetables and serve."],
      ingredients: ["200 g quinoa"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Parmesan Garlic Pasta"),
      title: "Parmesan Garlic Pasta",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/creamy-mushroom-pasta_wgnb3j.png",
      category: "dinner",
      cuisineId: cuisines[15].id,
      description: "Simple pasta with garlic and plenty of Parmesan.",
      prepTime: 5,
      cookTime: 15,
      difficulty: "easy",
      instructions: ["Toss hot pasta with garlic and grated Parmesan."],
      ingredients: ["250 g pasta"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Maple Glazed Salmon"),
      title: "Maple Glazed Salmon",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/honey-garlic-salmon_zfya0i.png",
      category: "dinner",
      cuisineId: cuisines[49].id,
      description: "Oven-roasted salmon with a sweet maple glaze.",
      prepTime: 5,
      cookTime: 18,
      difficulty: "easy",
      instructions: [
        "Brush the salmon with maple syrup and roast until flaky.",
      ],
      ingredients: ["2 salmon fillets"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Molten Chocolate Cups"),
      title: "Molten Chocolate Cups",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/chocolate-lava-cake_fqr7zl.png",
      category: "dessert",
      cuisineId: cuisines[3].id,
      description: "Warm individual chocolate desserts with soft centers.",
      prepTime: 10,
      cookTime: 12,
      difficulty: "hard",
      instructions: [
        "Bake the chocolate cups until the edges are set and centers soft.",
      ],
      ingredients: ["120 g chocolate"],
      servings: 4,
    },
    {
      slug: getUniqueRecipeSlug("Roasted Chickpea Salad"),
      title: "Roasted Chickpea Salad",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "salad",
      cuisineId: cuisines[20].id,
      description: "A crunchy salad topped with golden roasted chickpeas.",
      prepTime: 10,
      cookTime: 20,
      difficulty: "easy",
      instructions: [
        "Roast the chickpeas until crisp and add them to the salad.",
      ],
      ingredients: ["1 can chickpeas"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Creamy Garlic Chicken"),
      title: "Creamy Garlic Chicken",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/creamy-mushroom-pasta_wgnb3j.png",
      category: "dinner",
      cuisineId: cuisines[1].id,
      description: "Chicken simmered in a creamy garlic sauce.",
      prepTime: 10,
      cookTime: 25,
      difficulty: "medium",
      instructions: ["Simmer the chicken in garlic cream until tender."],
      ingredients: ["2 chicken breasts"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Lemon Butter Salmon"),
      title: "Lemon Butter Salmon",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/honey-garlic-salmon_zfya0i.png",
      category: "dinner",
      cuisineId: cuisines[5].id,
      description: "Tender salmon finished with fresh lemon and butter.",
      prepTime: 5,
      cookTime: 15,
      difficulty: "easy",
      instructions: [
        "Cook the salmon in butter and finish with fresh lemon juice.",
      ],
      ingredients: ["2 salmon fillets"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Chocolate Mousse Cake"),
      title: "Chocolate Mousse Cake",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/chocolate-lava-cake_fqr7zl.png",
      category: "dessert",
      cuisineId: cuisines[10].id,
      description: "A rich chocolate dessert topped with silky mousse.",
      prepTime: 20,
      cookTime: 25,
      difficulty: "hard",
      instructions: ["Bake the chocolate base and top it with chilled mousse."],
      ingredients: ["150 g chocolate"],
      servings: 6,
    },
    {
      slug: getUniqueRecipeSlug("Rainbow Couscous Bowl"),
      title: "Rainbow Couscous Bowl",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "lunch",
      cuisineId: cuisines[25].id,
      description: "Fluffy couscous topped with colorful fresh vegetables.",
      prepTime: 10,
      cookTime: 10,
      difficulty: "easy",
      instructions: ["Fluff the couscous and top it with fresh vegetables."],
      ingredients: ["200 g couscous"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Creamy Spinach Pasta"),
      title: "Creamy Spinach Pasta",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/creamy-mushroom-pasta_wgnb3j.png",
      category: "dinner",
      cuisineId: cuisines[15].id,
      description: "Creamy pasta with wilted spinach and Parmesan.",
      prepTime: 5,
      cookTime: 20,
      difficulty: "easy",
      instructions: ["Stir fresh spinach into the creamy pasta sauce."],
      ingredients: ["250 g pasta"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Garlic Chili Salmon"),
      title: "Garlic Chili Salmon",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/honey-garlic-salmon_zfya0i.png",
      category: "dinner",
      cuisineId: cuisines[39].id,
      description: "Salmon with a fragrant garlic and chili crust.",
      prepTime: 5,
      cookTime: 15,
      difficulty: "medium",
      instructions: [
        "Coat the salmon with garlic and chili before pan-frying.",
      ],
      ingredients: ["2 salmon fillets"],
      servings: 2,
    },
    {
      slug: getUniqueRecipeSlug("Easy Chocolate Souffle"),
      title: "Easy Chocolate Souffle",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/chocolate-lava-cake_fqr7zl.png",
      category: "dessert",
      cuisineId: cuisines[10].id,
      description: "Light chocolate souffles with a rich chocolate flavor.",
      prepTime: 15,
      cookTime: 15,
      difficulty: "hard",
      instructions: ["Bake the souffles until risen and serve immediately."],
      ingredients: ["100 g chocolate"],
      servings: 4,
    },
    {
      slug: getUniqueRecipeSlug("Warm Veggie Grain Bowl"),
      title: "Warm Veggie Grain Bowl",
      authorId: user.id,
      imageUrl:
        "https://res.cloudinary.com/dkvc3cs7o/image/upload/v1782997701/rainbow-buddha-bowl_bsbmt7.png",
      category: "lunch",
      cuisineId: cuisines[31].id,
      description: "Warm grains topped with roasted seasonal vegetables.",
      prepTime: 10,
      cookTime: 25,
      difficulty: "easy",
      instructions: ["Top cooked grains with freshly roasted vegetables."],
      ingredients: ["200 g rice"],
      servings: 2,
    },
  ]);

  console.log("added recipes");
}

seed();
